# Generated by Django 5.0.4 on 2025-12-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logos', '0002_orden_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito')], default='tarjeta', max_length=20),
        ),
    ]
