# Generated by Django 5.0.4 on 2025-12-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logos', '0003_alter_orden_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='banco_tarjeta',
            field=models.CharField(blank=True, help_text='Banco emisor de la tarjeta', max_length=50),
        ),
    ]
